### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by erwindon**
Cleaned up in 2 categories
1) solved all warnings as produced bij jslint with setting "esversion: 6"
2) removed unused parameters in 3 constructor calls

### CODE REVIEW

**Comment by maerteijn** [comment]
Thanks. When I have time I will add a linter which checks the pull requests for ES6 linter warnings / errors.

**Comment by maerteijn** [comment]
@erwindon Can you show me the exact settings / config of jslint you used? Then I can add it as post-commit hook.

**Comment by erwindon** [comment]
$ cat ~/.jshint 
{
"esversion": 6
}`

**Comment by erwindon** [comment]
and commandline:
`jshint --config ~/.jshint --exclude-path saltgui/static/scripts/JSON.sortify.js`
The excluded path is probably also possible in the jshint file.
JSON.sortify will be introduced later when we want JSON.stringify functionality, but then with sorted keys for dictionaries.

**Comment by maerteijn** [comment]
@erwindon Thnxm added this in #28 

You can add the exclude when needed  here https://github.com/maerteijn/SaltGUI/blob/master/package.json#L9

**Pull request merged**
