### PR TITLE
replace VAR with LET/CONST

### PR DESCRIPTION
**Pull request by erwindon**
I'm confusing myself often with the different use of `let` and `var`. Most of the new code that was contributed lately uses `let`. This PR changes all code to `let` and validates that code that no `var` still appear.

For viewers that want more details: see https://stackoverflow.com/questions/762011/whats-the-difference-between-using-let-and-var-to-declare-a-variable-in-jav

### CODE REVIEW

**Comment by maerteijn** [comment]
Nice!

You could also consider adding:
`"prefer-const": 2`

for vars that  are not mutated. But that I'll leave to you.

**Comment by erwindon** [comment]
I created issue #48 for that. It is much more work since each assignment needs to be inspected individually. Let's stick to this content for this PR.

**Comment by erwindon** [comment]
Ah, never mind.
`yarn jslint --fix` is great and does all the work...

**Comment by maerteijn** [comment]
👍

**Pull request merged**
